### ISSUE TITLE
Add Ofelia cron job config option to README

### ISSUE THREAD

**Issue by landure** [PPCM/docker-glpi#10]
Another possibility for cron tasks on stand-alone node is using [Ofelia](https://github.com/mcuadros/ofelia) to run cron job in containers using this configuration by labels:

```yaml
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.glpi-glpi-cron.schedule: '@every 2m'
      ofelia.job-exec.glpi-glpi-cron.command: /usr/bin/php '/var/www/glpi/front/cron.php'
      ofelia.job-exec.glpi-glpi-cron.user: apache
```

It would be nice to add the info to the README.
