### ISSUE TITLE
Working docker-compose.yml

### ISSUE THREAD

**Issue by howardshand** [PPCM/docker-glpi#15]
Good day,

Is anyone able to share a working docker-compose.yml? My attempt below seems to create some permissions issues and the GLPI install does not complete with the error "Database configuration file "/etc/glpi/config_db.php" is missing or is corrupted. You have to either restart the install process, either restore this file":

```
version: "3.2" 
name: some-help
services:
    mariadb:
        container_name: some-mariadb
        ports:
            - 3306:3306
        networks:
            - some-network
        environment:
            - MARIADB_USER=glpi-user
            - MARIADB_PASSWORD=glpi-password
            - MARIADB_ROOT_PASSWORD=root-password
            - MARIADB_DATABASE=glpi
        volumes:
            - ./data/mysql-dir:/var/lib/mysql
        image: mariadb:latest
    glpi-server:
        container_name: some-glpi
        ports:
            - 8089:80
        networks:
            - some-network
        environment:
            - MYSQL_HOST=some-mariadb
            - MYSQL_PORT=3306
            - MYSQL_ROOT_PASSWORD=root-password
            - MYSQL_USER=glpi-user
            - MYSQL_PASSWORD=glpi-password
            - MYSQL_DATABASE=glpi
            - LANG=fr_FR
            - TZ="Europe/Paris"
        volumes:
            - ./data/glpi-config:/etc/glpi
            - ./data/glpi-files:/var/glpi/files
            - ./data/glpi-plugins:/var/www/glpi/plugins
            - ./data/glpi-marketplace:/var/www/glpi/marketplace
        image: ppcm/glpi-server:latest
    glpi-cron-daemon:
        container_name: some-glpi-cron-daemon
        networks:
            - some-network
        environment:
            - CRON_SCHEDULE=*/2 * * * *
            - TZ="Europe/Paris"
        volumes:
            - ./data/glpi-config:/etc/glpi
            - ./data/glpi-files:/var/glpi/files
            - ./data/glpi-plugins:/var/www/glpi/plugins
            - ./data/glpi-marketplace:/var/www/glpi/marketplace
        image: ppcm/glpi-cron-daemon:latest
networks:
    some-network:
        name: some-network
```
