### ISSUE TITLE
Missing configuration

### ISSUE THREAD

**Issue by andrei1058** [PPCM/docker-glpi#3]
Fresh installation, latest tag.

![image](https://github.com/PPCM/docker-glpi/assets/13315829/9973391e-936e-4c03-80a4-18b5737be3d1)

![image](https://github.com/PPCM/docker-glpi/assets/13315829/674a659d-a747-4acd-b565-87b39b656599)

**Comment by belu33fr** [comment]
Hi,
Great job.
I have the same issue.
Thanks

**Comment by PPCM** [comment]
I confirm the issue.
I will take advantage of the new version 10.0.9 to correct the problem

**Comment by PPCM** [comment]
The new release was published
It correct the issue and update GLPI to 10.0.9 (see changes [here](https://github.com/PPCM/docker-glpi/releases/tag/10.0.9-1))

**Comment by PPCM** [comment]
I created a new instance from scratch with 10.0.11-1 and it works fine
Can you give more information about your environment, the used database, etc.

**Comment by 3gmgithub** [comment]
> I created a new instance from scratch with 10.0.11-1 and it works fine Can you give more information about your environment, the used database, etc.

Debian 12, Mariadb Latest, fresh install

**Comment by PPCM** [comment]
Be a little bit more explicit if you want help
Did you create the database by your self, how did you create your pods, docker/kubernetes, ...

**Comment by 3gmgithub** [comment]
Ok so after some troubleshooting, looks like when I first did this I did not have the depends_on in the docker compose.
After adding that and starting over, I got it working on the latest version.
However, you do have to do the following to make it work:

1) docker compose up -d 
2) docker compose down
3) docker compose up -d

For some reason on first launch it does not work, but consistently on the second one it does.

**Comment by PPCM** [comment]
This is because you need to wait that Mariadb completely starts
Here is your docker-compose with a healthcheck that will wait:

```
# networks
# create a network 'glpi_net' in mode 'bridge'
networks:
  glpi_net:
    driver: bridge
volumes:
  mysql-dir:
  glpi-config:
  glpi-files:
  glpi-plugins:
  glpi-marketplace:

services:

  some-mariadb:
    env_file: .env
    image: 'mariadb:latest'
    ports:
      - '3306:3306'
    networks:
      - glpi_net
    volumes:
      - "mysql-dir:/var/lib/mysql"
    healthcheck:
      test: "/usr/bin/mariadb --user=\"${MARIADB_USER}\" --password=\"${MARIADB_PASSWORD}\" --execute \"SHOW DATABASES;\" \"${MARIADB_DATABASE}\""
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

  some-glpi:
    env_file: .env
    image: "ppcm/glpi-server:${APP_VER}"
    ports:
      - '8089:80'
    networks:
      - glpi_net
    depends_on:
      some-mariadb:
        condition: service_healthy
    volumes:
      - "glpi-config:/etc/glpi"
      - "glpi-files:/var/glpi/files"
      - "glpi-plugins:/var/www/glpi/plugins"
      - "glpi-marketplace:/var/www/glpi/marketplace"

  some-glpi-cron:
    env_file: .env
    image: "ppcm/glpi-cron-daemon:${APP_VER}"
    networks:
      - glpi_net
    depends_on:
      - some-glpi
    volumes:
      - "glpi-config:/etc/glpi"
      - "glpi-files:/var/glpi/files"
      - "glpi-plugins:/var/www/glpi/plugins"
      - "glpi-marketplace:/var/www/glpi/marketplace"
```

Your request put me in mind that I should propose a docker-compose file
